[build]
  base = "/"
  publish = "client/public/index.html"
  command  = "CI= npm run build"
  functions = "server/"
[[redirects]]
  from = "/*"
  to = "/client/public/index.html"
  status = 200
