[build]
  base = "/"
  publish = "client/public/index.html"
  command  = "npm run build"
  functions = "/server/index.js"
[[redirects]]
  from = "/*"
  to = "/client/public/index.html"
  status = 200